"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
var apollo_server_1 = require("apollo-server");
exports.typeDefs = apollo_server_1.gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    type Contract {\n        address: String!\n        amount: Float    \n    }\n\n    type Transaction {\n        hash: String\n        amount: Float\n        type: String\n        time: String\n    }\n\n    type Query {\n        contract: Contract\n        transactions: TransactionLoaded!\n    }\n\n    type Mutation {\n        checkNewEvent: TransactionPublished\n    }\n\n    type TransactionPublished {\n        status:String\n        data: Transaction\n    }\n\n    type TransactionLoaded {\n        status: String\n        data: [Transaction!]\n    }\n\n    type Subscription {\n        transaction: TransactionPublished\n        getTransactions: TransactionLoaded\n    }\n"], ["\n    type Contract {\n        address: String!\n        amount: Float    \n    }\n\n    type Transaction {\n        hash: String\n        amount: Float\n        type: String\n        time: String\n    }\n\n    type Query {\n        contract: Contract\n        transactions: TransactionLoaded!\n    }\n\n    type Mutation {\n        checkNewEvent: TransactionPublished\n    }\n\n    type TransactionPublished {\n        status:String\n        data: Transaction\n    }\n\n    type TransactionLoaded {\n        status: String\n        data: [Transaction!]\n    }\n\n    type Subscription {\n        transaction: TransactionPublished\n        getTransactions: TransactionLoaded\n    }\n"])));
var templateObject_1;
